# -*- coding: utf-8 -*-
"""code_anomoly_detect .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGFvmCSnSQ1qZMrKpLrNpT5jvkUZz3Xp
"""

!pip install pandas numpy matplotlib seaborn scipy

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

!pip install ucimlrepo

from ucimlrepo import fetch_ucirepo
import pandas as pd

# Load Occupancy Detection dataset
dataset = fetch_ucirepo(id=357)

# Features and targets
X = dataset.data.features
y = dataset.data.targets

# Fix: rename column properly
y = y.rename(columns={y.columns[0]: "Occupancy"})

# Merge into single DataFrame
data = pd.concat([X, y], axis=1)

print(" Dataset Loaded Successfully")
print("Shape:", data.shape)
print(data.head())

#  Convert 'date' column into datetime properly
data['date'] = pd.to_datetime(
    data['date'],
    format="%Y-%m-%d %H:%M:%S",   # matches dataset format
    errors='coerce'               # bad values become NaT instead of error
)

#  Drop rows where date could not be parsed
data = data.dropna(subset=['date'])

#  Sort by time
data = data.sort_values(by='date').reset_index(drop=True)

print(data['date'].head())

# Plot only the first 500 rows
plt.figure(figsize=(14,6))
plt.plot(data['date'][:500], data['Temperature'][:500], label="Temperature")
plt.xlabel("Time")
plt.ylabel("Temperature (°C)")
plt.title("Temperature Over Time (First 500 rows)")
plt.legend()
plt.show()

# Humidity
plt.figure(figsize=(14,6))
plt.plot(data['date'][:500], data['Humidity'][:500], label="Humidity", color='orange')
plt.xlabel("Time")
plt.ylabel("Humidity (%)")
plt.title("Humidity Over Time (First 500 rows)")
plt.legend()
plt.show()

# Light
plt.figure(figsize=(14,6))
plt.plot(data['date'][:500], data['Light'][:500], label="Light", color='green')
plt.xlabel("Time")
plt.ylabel("Light (Lux)")
plt.title("Light Over Time (First 500 rows)")
plt.legend()
plt.show()

# CO2
plt.figure(figsize=(14,6))
plt.plot(data['date'][:500], data['CO2'][:500], label="CO2", color='red')
plt.xlabel("Time")
plt.ylabel("CO2 (ppm)")
plt.title("CO2 Over Time (First 500 rows)")
plt.legend()
plt.show()

!pip install ucimlrepo

# -----------------------------
# Step 1: Load dataset
# -----------------------------
from ucimlrepo import fetch_ucirepo
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Occupancy Detection dataset (UCI id=357)
dataset = fetch_ucirepo(id=357)

# Features and target
X = dataset.data.features
y = dataset.data.targets.rename(columns={dataset.data.targets.columns[0]: "Occupancy"})

# Merge into one DataFrame
data = pd.concat([X, y], axis=1)

# Convert 'date' column into datetime
data['date'] = pd.to_datetime(data['date'], format="%Y-%m-%d %H:%M:%S", errors='coerce')
data = data.dropna(subset=['date'])
data = data.sort_values(by='date').reset_index(drop=True)

print("✅ Dataset Loaded")
print("Shape:", data.shape)
print(data.head())

# -----------------------------
# Step 2: Correlation Heatmap
# -----------------------------
numeric_data = data.select_dtypes(include=['float64', 'int64'])  # only numeric cols

plt.figure(figsize=(10,6))
sns.heatmap(numeric_data.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap (Numeric Features Only)")
plt.show()

# Step 2: Statistical Summary
summary = data.describe()
print(summary)

from scipy.stats import zscore
import pandas as pd

# Ensure CO2 column is numeric
data['CO2'] = pd.to_numeric(data['CO2'], errors='coerce')

# Calculate Z-scores for CO2
data['CO2_zscore'] = pd.Series(zscore(data['CO2']), index=data.index)

# Detect anomalies where |z| > 3
anomalies_co2 = data.loc[data['CO2_zscore'].abs() > 3]

print("Number of CO2 anomalies:", len(anomalies_co2))

from scipy.stats import zscore
import pandas as pd

# Ensure CO2 column is numeric
data['CO2'] = pd.to_numeric(data['CO2'], errors='coerce')

# Calculate Z-scores for CO2
data['CO2_zscore'] = pd.Series(zscore(data['CO2']), index=data.index)

# Detect anomalies where |z| > 3
anomalies_co2 = data.loc[data['CO2_zscore'].abs() > 3]

print("Number of CO2 anomalies:", len(anomalies_co2))

plt.figure(figsize=(14,6))
plt.plot(data['date'][:500], data['CO2'][:500], label="CO2", color='blue')
plt.scatter(anomalies_co2['date'], anomalies_co2['CO2'], color='red', label="Anomaly")
plt.xlabel("Time")
plt.ylabel("CO2 (ppm)")
plt.title("CO2 Anomalies (Z-score Method)")
plt.legend()
plt.show()

from scipy.stats import zscore
import matplotlib.pyplot as plt

# List of sensor columns
sensors = ['Temperature', 'Humidity', 'Light', 'CO2']

for sensor in sensors:
    # Convert to numeric just in case
    data[sensor] = pd.to_numeric(data[sensor], errors='coerce')

    # Drop NaN values
    data = data.dropna(subset=[sensor])

    # Z-score calculation
    z_col = sensor + '_zscore'
    data[z_col] = zscore(data[sensor])

    # Detect anomalies
    anomalies = data[data[z_col].abs() > 3]
    print(f"Number of anomalies in {sensor}: {len(anomalies)}")

    # Plot anomalies
    plt.figure(figsize=(14,6))
    plt.plot(data['date'][:500], data[sensor][:500], label=sensor, color='blue')
    plt.scatter(anomalies['date'], anomalies[sensor], color='red', label="Anomaly")
    plt.xlabel("Time")
    plt.ylabel(sensor)
    plt.title(f"{sensor} Anomalies (Z-score Method)")
    plt.legend()
    plt.show()

Q1 = data['CO2'].quantile(0.25)
Q3 = data['CO2'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

anomalies_iqr_co2 = data[(data['CO2'] < lower_bound) | (data['CO2'] > upper_bound)]
print("Number of CO2 anomalies (IQR):", len(anomalies_iqr_co2))

sensors = ['Temperature', 'Humidity', 'Light', 'CO2']
anomaly_counts_iqr = {}

for sensor in sensors:
    Q1 = data[sensor].quantile(0.25)
    Q3 = data[sensor].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    anomalies_iqr = data[(data[sensor] < lower_bound) | (data[sensor] > upper_bound)]
    anomaly_counts_iqr[sensor] = len(anomalies_iqr)

# Show results
print("📊 IQR Anomaly Counts Per Sensor:")
for sensor, count in anomaly_counts_iqr.items():
    print(f"{sensor}: {count}")

import pandas as pd

# Replace these with your Z-score anomaly counts
anomaly_counts_zscore = {
    'Temperature': 520,   # (example values – use your actual results)
    'Humidity': 10,
    'Light': 210,
    'CO2': 1500
}

# Use IQR results from Step 7
anomaly_counts_iqr = {
    'Temperature': 519,
    'Humidity': 0,
    'Light': 183,
    'CO2': 1449
}

# Create summary table
summary = pd.DataFrame({
    "Z-score": anomaly_counts_zscore,
    "IQR": anomaly_counts_iqr
})

print(" Anomaly Summary Table:")
print(summary)

import matplotlib.pyplot as plt
from scipy.stats import zscore

# Sensors list
sensors = ['Temperature', 'Humidity', 'Light', 'CO2']

# Create subplots (2x2 grid)
fig, axes = plt.subplots(2, 2, figsize=(16,10))
axes = axes.flatten()

for i, sensor in enumerate(sensors):
    # Ensure numeric
    data[sensor] = pd.to_numeric(data[sensor], errors='coerce')
    data = data.dropna(subset=[sensor])

    # Z-score
    data[sensor + '_zscore'] = zscore(data[sensor])

    # Anomalies detection
    anomalies = data[data[sensor + '_zscore'].abs() > 3]

    # Plot
    axes[i].plot(data['date'][:500], data[sensor][:500], label=sensor, color='blue')
    axes[i].scatter(anomalies['date'], anomalies[sensor], color='red', s=20, label='Anomaly')

    axes[i].set_title(f"{sensor} Anomalies (Z-score)")
    axes[i].set_xlabel("Time")
    axes[i].set_ylabel(sensor)
    axes[i].legend()

plt.tight_layout()
plt.show()